env:
  global:
    - # USERNAME
    - secure: rIDvn/HgAAtrgGWg1jF/a8gI1w/8e14BRq8vm18kM2WWoWvl9kYF5YEqv9Pk9Yde3AkZX+W6MWZ1NZE0Vw5igmrW1ogfUcbgmu5mevsXAAL2E9t5xMrxijm8SVyM3yWdTbTfb6tHlfKim8Vy1asNgy4GbTNX7TC/s+UAjRbpaD8/iENvnBNJ7uX+GNY3XXO6bnD4wsyRAd4sMtO808Rkd+M4V4QIsmsGEnz+WHdYACsRt7qIwibcE9rVC/UyDSklnhtzlcjMWJzn1iPd2rFUwn3pHQCXRm8RP/9xKnX//wIKlu1Bj1vWOApW8TA8TwjzSojEvV8FPmNljI0QbY1PHiM0y6LdVC5qsxIBNfkqxOLKNJY66enSTxz9Hb6kmh1GkF4Ubgdyxjq+Lzz73aE78dMoHdLQE7Nn9CVl4Vwk4bqGujjHZPNJJDT1W2WenIfOyYxSkfNwkRmS4a6qXZV4EK6gYJrt7YfVOUTCIFsomv8dLfHARi4lIwjLAAknGLxjKDKZbrBGRQeE+1g+6eO1xG4szkIvY0WbOxzutoAvlgLBjZTdE2T8jIwTZokxR1x9dRZ2G+XbVYt9N1VfyzX5iER6n4Og84PbMxCszKc4RHUgc5yP8F2J76End+jSOc1IdCuKhZueBm/hfWvqaFIT3ErTHchrRjf5tbn1FbCwEu0=
    - # PASSWORD
    - secure: dfahNlwhtLHvLsSdkncDSi6947ssRb1pdxMY4hzyLXv42lL3aT8uAQ5NW06Ly+vwAKQAUQrkDQ37SsEG28uzFFoMbMVm1M8/QlrD5By4cg+MZXI++nFxlLEZvD79RQku6cH8qryYLLiTOSBRYNcd3OTP7dzfum77BamWUZYWNr5TshojvXTsGDejIvjyNXIRf6KuIBzDU3EwnQTpSb0BjeMsMYM24Hnz9/B+COv5Zq0/O+UYbWHYXizufJs0iD2hczTFFpH49aJ51DQQUWD72dj2lAWp9n7w+e3ndgaU2at9mpu/X38GCr+SpEqz1h/8d2KdNM2tNAXfm9mlIE4qnX7XCPYBLIiVtU9wBwANki+oPftuCXmBacNL85wsKYVrmadRIUTjcY5fa3MbHj5veTgImKpJCeBL/WL64CAlEXwfYI7Sf67oAxeukoySMQElRD8yx2kllhOzB2ffobhzIHvrwpH8m89r+xtwdk3t2FL9PfU/R09HE4E6bOB00V05pGhGp9iKWuTYWXYbHgQfnla7NRxcqSAglOdVaoKjCjL0EZR7fJoNkzcOAQ5nOclOwqREMgD9brasS+ym2M4NxWG3xJWH485v8msPsmkMVZauq5YMlzmU4l7r8ikl7O6d4euv5Y6OOfUnZiTtgtIun9q0vrDspPjOU2IUfdf2BTM=
dist: trusty
language: java
jdk:
# - oraclejdk8
# - oraclejdk11
# - openjdk10
# - openjdk11
  - openjdk12

script:
  - ./gradlew -q -Pusername=$USERNAM -Ppassword=$PASSWORD testScript
